[package]
name = "berg-chat"
version = "0.1.0"
edition = "2021"

[dependencies]
local-ip-address = "0.5.3"
threads_pool = "0.2.6"
[local-ip-address]
proc-macro2 = "1.0.56" # Example of pinning to an older version
